//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaming_club
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public game()
        {
            this.date_of_game_library = new HashSet<date_of_game_library>();
            this.tournaments = new HashSet<tournament>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int id_genre { get; set; }
        public int id_thematics { get; set; }
        public int age_limit { get; set; }
        public string image { get; set; }
        public int id_exclusive { get; set; }
        public int id_category { get; set; }
        public string price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<date_of_game_library> date_of_game_library { get; set; }
        public virtual exclusive_game exclusive_game { get; set; }
        public virtual game_category game_category { get; set; }
        public virtual game_genre game_genre { get; set; }
        public virtual game_thematic game_thematic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tournament> tournaments { get; set; }
    }
}
