//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaming_club
{
    using System;
    using System.Collections.Generic;
    
    public partial class players_of_game_library
    {
        public int id { get; set; }
        public int id_game_library { get; set; }
        public int id_user_data { get; set; }
        public int age { get; set; }
    
        public virtual date_of_game_library date_of_game_library { get; set; }
        public virtual User_data User_data { get; set; }
    }
}
