//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaming_club
{
    using System;
    using System.Collections.Generic;
    
    public partial class tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tournament()
        {
            this.players_of_tournament = new HashSet<players_of_tournament>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_game { get; set; }
        public Nullable<int> id_userData { get; set; }
        public Nullable<System.DateTime> date_of_tournament { get; set; }
        public Nullable<int> min_age { get; set; }
        public Nullable<int> price { get; set; }
        public string title { get; set; }
        public string description { get; set; }
    
        public virtual game game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<players_of_tournament> players_of_tournament { get; set; }
        public virtual User_data User_data { get; set; }
    }
}
